# runtime image including CA certs and tzdata
FROM gcr.io/distroless/static-debian13:nonroot
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/terranotate /go/bin/terranotate
# Expose port for publishing as web service
# EXPOSE 8081
# Run the binary.
ENTRYPOINT ["/go/bin/terranotate"]
